[package]
name = "broken-link-checker"
version = "1.1.0"
edition = "2024"
description = "Broken link checker: crawl a URL or local file, find links, report 404 and 5xx"
readme = "README.md"
license = "MIT"
repository = "https://github.com/lohit-dev/broken-link-checker"
homepage = "https://github.com/lohit-dev/broken-link-checker"
documentation = "https://docs.rs/broken-link-checker"
keywords = ["link", "checker", "crawl", "broken-links", "cli"]
categories = ["command-line-utilities", "web-programming"]
authors = ["lohit-dev"]
exclude = ["target", "*.pdb", ".git"]

[[bin]]
name = "ble"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.58", features = ["derive"] }
config = "0.15.19"
eyre = "0.6.12"
reqwest = "0.13.2"
serde = { version = "1.0.228", features = ["derive"] }
url = "2.5.8"
tokio = { version = "1.49.0", features = ["rt-multi-thread", "macros"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
scraper = "0.25.0"

[dev-dependencies]
wiremock = "0.6.5"
